version: '3.9'
# LOCAL DEV
services:
  devtools:
    container_name: devtools
    user: 1000:1000
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: .env
    volumes:
      # Mount local codebase to reflect changes for local dev
      - .:/app
    ports:
      - 3000:3000
